// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBffaLE8njtlxvRdN9KZzw6F_jmVIapX7E',
    appId: '1:365045941934:android:e2f8830196664e953c8f3f',
    messagingSenderId: '365045941934',
    projectId: 'duakataapi-1548570152943',
    databaseURL: 'https://duakataapi-1548570152943.firebaseio.com',
    storageBucket: 'duakataapi-1548570152943.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoW8SBrT0UilNjYiXT17GgZHf9Ds0oZjs',
    appId: '1:365045941934:ios:1c8330a2193b3ea43c8f3f',
    messagingSenderId: '365045941934',
    projectId: 'duakataapi-1548570152943',
    databaseURL: 'https://duakataapi-1548570152943.firebaseio.com',
    storageBucket: 'duakataapi-1548570152943.appspot.com',
    androidClientId: '365045941934-4f93ln9ppl3tl798c46131r3ckv31voc.apps.googleusercontent.com',
    iosClientId: '365045941934-jgmp4r5oa9bp4v0s017201h93lbrubl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.abzeno',
  );
}
